# Generated by Django 3.2.3 on 2021-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210518_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip', models.CharField(default='', max_length=20)),
                ('country', models.CharField(choices=[('US', 'USA'), ('IT', 'ITALY'), ('IND', 'INDIA')], max_length=20)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
