# Generated by Django 3.2.3 on 2021-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='order_table',
        ),
    ]
