# Generated by Django 3.2.3 on 2021-05-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_content_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='country',
        ),
    ]
